services:
    nginx:
        image: nginx_base:v1
        container_name: nginx
        volumes:
            - nginx-conf:/etc/nginx/
        ports:
            - '80:80'
        networks:
            macvlan_net:
                ipv4_address: 192.168.1.10
        stdin_open: true   # equivalent to -i
        tty: true          # equivalent to -t
        restart: unless-stopped
    lab1:
        image: metasploitable2:v1
        container_name: metasploitable2
        command: sh -c "/bin/services.sh && bash"
        depends_on:
            - nginx
        ports:
            - '8081:80'
        networks:
            macvlan_net:
                ipv4_address: 192.168.1.11
        stdin_open: true   # equivalent to -i
        tty: true          # equivalent to -t
        restart: unless-stopped
    lab2:
        image: sagikazarmark/dvwa:latest
        container_name: dvwa
        depends_on:
            - nginx
        ports:
            - '8082:80'
        networks:
            macvlan_net:
                ipv4_address: 192.168.1.12
        stdin_open: true   # equivalent to -i
        tty: true          # equivalent to -t
        restart: unless-stopped
    lab3:
        image: bkimminich/juice-shop:latest
        container_name: juice-shop
        depends_on:
            - nginx
        ports:
            - '8083:3000'
        networks:
            macvlan_net:
                ipv4_address: 192.168.1.13
        stdin_open: true   # equivalent to -i
        tty: true          # equivalent to -t
        restart: unless-stopped
    lab4:
        image: raesene/bwapp:latest
        container_name: bwapp
        depends_on:
            - nginx
        ports:
            - '8084:80'
        networks:
            macvlan_net:
                ipv4_address: 192.168.1.14
        stdin_open: true   # equivalent to -i
        tty: true          # equivalent to -t
        restart: unless-stopped
        
networks:
    macvlan_net: 
        external: true  
        name: macvlan_net
        
volumes:
  nginx-conf:
    driver: local
    driver_opts:
      type: none
      device: /opt/files/nginx-proxy/nginx/
      o: bind
